# Generated by Django 4.0.1 on 2022-02-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='msisdn',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='org_account_balance',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='status_reason',
        ),
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw'), ('T', 'Transfer')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.IntegerField(choices=[(1032, 'Cancelled'), (0, 'Complete')], default=0),
        ),
    ]
