# Generated by Django 4.0.1 on 2022-02-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_transactions_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='bill_reference_number',
            new_name='mpesa_receipt_number',
        ),
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.IntegerField(choices=[(1032, 'Cancelled'), (0, 'Complete'), (1, 'Pending')], default=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
