# Generated by Django 4.0.1 on 2022-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_bill_reference_number_transactions_mpesa_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(max_length=20),
        ),
    ]
