# Generated by Django 4.0.1 on 2022-02-23 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='description',
        ),
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
