# Generated by Django 4.0.1 on 2022-02-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_transactions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
