# Generated by Django 4.0.1 on 2022-01-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_goal_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_id',
            field=models.UUIDField(null=True),
        ),
    ]
