# Generated by Django 4.0.1 on 2022-02-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_goal_goal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='thumbnail',
            field=models.ImageField(default='pigibank-default.png', upload_to='goals'),
        ),
    ]
