# Generated by Django 4.0.1 on 2022-02-14 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0004_alter_goal_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_saving',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Finished')], default=0),
        ),
        migrations.CreateModel(
            name='LockedSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_id', models.UUIDField()),
                ('thumbnail', models.ImageField(default='pigibank-default.png', upload_to='locked_savings')),
                ('item_name', models.CharField(max_length=50)),
                ('principal_deposit', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(choices=[(3, 'Quarterly'), (6, 'Semi Anually'), (12, 'Anually')], max_length=1)),
                ('current_total', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Finished')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
