# Generated by Django 4.0.1 on 2022-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_goal_current_saving_goal_status_lockedsavings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockedsavings',
            name='duration',
            field=models.IntegerField(choices=[(3, 'Quarterly'), (6, 'Semi Anually'), (12, 'Anually')]),
        ),
    ]
