# Generated by Django 4.0.1 on 2022-02-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_generalwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='thumbnail',
            field=models.ImageField(default='goals/pigibank-default.png', upload_to='goals'),
        ),
    ]
