# Generated by Django 4.0.1 on 2022-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_alter_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='thumbnail',
            field=models.ImageField(default='goals/pigibank-default.jpg', upload_to='goals'),
        ),
        migrations.AlterField(
            model_name='lockedsavings',
            name='thumbnail',
            field=models.ImageField(default='pigibank-default.jpg', null=True, upload_to='locked_savings'),
        ),
    ]
