# Generated by Django 4.0.1 on 2022-02-20 16:09

import authentication.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('thumbnail', models.ImageField(default='/profile/pigibank-default.png', upload_to='profile')),
                ('user_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True)),
                ('password', models.CharField(max_length=300, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('id_number', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into our admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. ')),
                ('id_pic_front', models.ImageField(blank=True, null=True, upload_to='id_image/')),
                ('id_pic_back', models.ImageField(blank=True, null=True, upload_to='id_image/')),
                ('is_verified', models.BooleanField(default=False, help_text='Tells whether a user is verified or not using their ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('visibility', models.IntegerField(blank=True, default=1, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=300, null=True)),
                ('main_user_id', models.IntegerField(default=0)),
                ('account_balance', models.IntegerField(default=0.0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('refered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_added'],
            },
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
    ]
