# Generated by Django 4.0.1 on 2022-01-17 09:57

import authentication.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into our admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. ')),
                ('id_pic_front', models.ImageField(blank=True, null=True, upload_to='id_image/')),
                ('id_pic_back', models.ImageField(blank=True, null=True, upload_to='id_image/')),
                ('is_verified', models.BooleanField(default=False, help_text='Tells whether a user is verified or not using their ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('visibility', models.IntegerField(blank=True, default=1, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=300, null=True)),
                ('refered_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
    ]
