# Generated by Django 4.0.1 on 2022-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
