# Generated by Django 4.0.1 on 2022-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_id_number_myuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
