# Generated by Django 4.0.1 on 2022-02-10 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_myuser_main_user_id_alter_myuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='thumbail',
            field=models.ImageField(default='pigibank-default.png', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
