# Generated by Django 4.0.1 on 2022-02-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_myuser_thumbail_alter_myuser_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='thumbail',
            new_name='thumbnail',
        ),
    ]
