# Generated by Django 4.0.1 on 2022-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_myuser_refered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='account_balance',
            field=models.IntegerField(default=0.0),
        ),
    ]
