# Generated by Django 4.0.1 on 2022-02-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_myuser_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='thumbnail',
            field=models.ImageField(default='/profile/pigibank-default.png', upload_to='profile'),
        ),
    ]
