# Generated by Django 4.0.1 on 2022-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='isPositive',
            field=models.BooleanField(default=True),
        ),
    ]
